package com.matthewtamlin.shamir.app.secretsharing.creation;

public enum DismissibleError {
  SECRET_FILE_DOES_NOT_EXIST,
  SECRET_FILE_IS_TOO_LARGE,
  OUTPUT_DIRECTORY_CANNOT_BE_CREATED,
  OUTPUT_DIRECTORY_IS_NOT_CLEAN,
  CANNOT_CREATE_SHARE_FILE,
  CANNOT_WRITE_TO_SHARE_FILE,
  CANNOT_CREATE_RECOVERY_SCHEME_FILE,
  CANNOT_WRITE_TO_RECOVERY_SCHEME_FILE,
  FILESYSTEM_ERROR
}