package com.matthewtamlin.shamir.app.secretsharing.recovery;

public enum DismissibleError {
  SHARE_FILE_DOES_NOT_EXIST,
  SHARE_FILE_IS_MALFORMED,
  RECOVERY_SCHEME_FILE_DOES_NOT_EXIST,
  RECOVERY_SCHEME_IS_MALFORMED,
  OUTPUT_DIRECTORY_CANNOT_BE_CREATED,
  OUTPUT_DIRECTORY_IS_NOT_CLEAN,
  CANNOT_CREATE_RECOVERED_SECRET_FILE,
  CANNOT_WRITE_TO_RECOVERED_SECRET_FILE,
  RECOVERY_FAILED,
  FILESYSTEM_ERROR
}